[features]
seeds = false
skip-lint = false

[registry]
url = "https://anchor.so/"

[programs.devnet]
solana_example_counter = "EocvjwaAyd7pxUqYNQCyvBD9pKTip1axngq48W4bZXUu"
solana_example_token = "F1ypE56CREbfeCBVreAWJnB8t8VthMftpowviNhKELNY"
solana_example_constraints = "3AVrFfBQdN5UR9sdaEUjwkmYBcqLKAknhqqamZ9idPP2"

[programs.localnet]
solana_example_counter = "EocvjwaAyd7pxUqYNQCyvBD9pKTip1axngq48W4bZXUu"
solana_example_token = "F1ypE56CREbfeCBVreAWJnB8t8VthMftpowviNhKELNY"
solana_example_constraints = "3AVrFfBQdN5UR9sdaEUjwkmYBcqLKAknhqqamZ9idPP2"

[provider]
cluster = "devnet"
devnet = "api.devnet.solana.com"
wallet = "/Users/phong/Projects/RustBeginning/solana-programs-anchor/keypair/dev.json"

[scripts]
test =  "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
test_solana_example_token = "ts-mocha -p ./tsconfig.json -t 1000000 tests/solana_example_token.ts"
test_solana_example_counter = "ts-mocha -p ./tsconfig.json -t 1000000 tests/solana_example_counter.ts"
test_solana_example_constraints = "ts-mocha -p ./tsconfig.json -t 1000000 tests/solana_example_constraints.ts"
