[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_helloworld = "GjzSfNKNVjdc58HJrhYDPfuv5h8ifkcNnfMhWAf5j8zF"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "localnet"
devnet = "api.devnet.solana.com"
wallet = "/Users/phong/Projects/RustBeginning/solana-programs-anchor/keypair/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
