[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "localnet"
devnet = "api.devnet.solana.com"
wallet = "/Users/phong/Projects/RustBeginning/solana-programs-anchor/keypair/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
